In [44]:
import numpy as np
matrix=np.array([[2,4,6],[3,5,9],[6,7,5]])
print(matrix)

[[2 4 6]
 [3 5 9]
 [6 7 5]]


In [46]:
mean=np.mean(matrix)
print (mean)

5.222222222222222


In [48]:
median=np.median(matrix)
print (median)

5.0


In [50]:
from scipy import stats
mode=stats.mode(matrix,axis=1) #axis=0 for column and axis=1 for row
print(mode)

ModeResult(mode=array([2, 3, 5], dtype=int64), count=array([1, 1, 1], dtype=int64))


In [54]:
d=np.linalg.det(matrix)
print(d)

26.000000000000014


In [56]:
inverse=np.linalg.inv(matrix)
print(inverse)

[[-1.46153846e+00  8.46153846e-01  2.30769231e-01]
 [ 1.50000000e+00 -1.00000000e+00  8.54017711e-18]
 [-3.46153846e-01  3.84615385e-01 -7.69230769e-02]]
